version: '2'
services:
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    networks:
      - kafkanet
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka_container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${zookeeper_ip}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafkanet
    depends_on:
      - zookeeper

networks:
  kafkanet:
    driver: bridge